import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (file) => readFile(path.join(rootDir, file), "utf8");

const readme = await read("README.md");
const docsIndex = await read("docs/README.md");
const usage = await read("docs/USAGE.md");
const gettingStarted = await read("docs/GETTING_STARTED.md");
const installation = await read("docs/INSTALLATION.md");
const configuration = await read("docs/CONFIGURATION.md");
const pdfStrategy = await read("docs/PDF_STRATEGY.md");
const aiFirstLayout = await read("docs/AI_FIRST_LAYOUT.md");
const wholePaperAnalysis = await read("docs/WHOLE_PAPER_ANALYSIS.md");
const troubleshooting = await read("docs/TROUBLESHOOTING.md");
const migration = await read("docs/MIGRATION.md");
const visualProvider = await read("docs/VISUAL_PROVIDER.md");
const deployment = await read("docs/DEPLOYMENT.md");
const indexHtml = await read("public/index.html");
const appSource = await read("public/app.js");
const appStyles = await read("public/styles.css");
const serverSource = await read("server.js");
const packageJson = JSON.parse(await read("package.json"));

assert.ok(readme.split(/\r?\n/).length <= 120, "README should stay concise and link to docs for detail");
assert.match(readme, /\[文档目录\]\(docs\/README\.md\)/);
assert.match(readme, /\[具体怎么用\]\(docs\/USAGE\.md\)/);
assert.match(readme, /\(docs\/GETTING_STARTED\.md\)/);
assert.match(readme, /git clone https:\/\/github\.com\/Phyll1s0\/PaperLens\.git/);
assert.match(readme, /npm run data:export/);

assert.equal(packageJson.scripts["data:export"], "node scripts/export-portable-data.mjs");
assert.equal(packageJson.scripts["data:import"], "node scripts/import-portable-data.mjs");

assert.match(docsIndex, /\[具体怎么用\]\(USAGE\.md\)/);
assert.match(docsIndex, /\[安装和运行\]\(INSTALLATION\.md\)/);
assert.match(docsIndex, /\[PDF 解析策略\]\(PDF_STRATEGY\.md\)/);
assert.match(docsIndex, /\[迁移和备份\]\(MIGRATION\.md\)/);

assert.match(usage, /# 如何用 PaperLens 精读一篇论文/);
assert.match(usage, /测试连接/);
assert.match(usage, /质量报告/);
assert.match(usage, /分段调试/);
assert.match(usage, /下载Word/);

assert.match(gettingStarted, /# PaperLens Getting Started/);
assert.match(gettingStarted, /Kimi Code Direct/);
assert.match(gettingStarted, /DeepSeek/);
assert.match(gettingStarted, /不需要 Claude CLI/);
assert.match(gettingStarted, /npm run data:export/);
assert.match(gettingStarted, /npm run data:import -- \/path\/to\/paperlens-data-时间戳\.tar\.gz --yes/);
assert.match(gettingStarted, /质量报告/);
assert.match(gettingStarted, /分段调试/);

assert.match(installation, /PaperLens-local\.tar\.gz/);
assert.match(installation, /普通用户第一次使用不需要先装齐所有可选工具/);
assert.match(configuration, /PAPERLENS_PROXY_URL/);
assert.match(configuration, /PAPERLENS_OCR_LANGUAGE/);
assert.match(pdfStrategy, /# PDF 解析策略/);
assert.match(pdfStrategy, /AI-first PDF/);
assert.match(pdfStrategy, /Poppler、OCRmyPDF、Tesseract、Docker 和 Claude CLI 都应该是“增强能力”/);
assert.match(aiFirstLayout, /# AI-first Layout Design/);
assert.match(aiFirstLayout, /normalizeAiLayoutResult/);
assert.match(aiFirstLayout, /hybrid/);
assert.match(wholePaperAnalysis, /# Whole-paper Deep Analysis Design/);
assert.match(wholePaperAnalysis, /全文长思考/);
assert.match(wholePaperAnalysis, /防偷懒校验/);
assert.match(wholePaperAnalysis, /lib\/deep-paper-plan\.js/);
assert.match(wholePaperAnalysis, /buildSectionDigestsForPaper/);
assert.match(wholePaperAnalysis, /attachSectionDigestsToPaper/);
assert.match(troubleshooting, /页面打不开/);
assert.match(migration, /npm run data:export/);
assert.match(migration, /PAPERLENS_STORAGE=sqlite/);
assert.match(visualProvider, /PAPERLENS_VISUAL_PROVIDER/);
assert.match(deployment, /PAPERLENS_DEPLOYMENT_MODE=public/);

assert.match(appSource, /function getProviderGuideSteps/);
assert.match(appSource, /选择入口/);
assert.match(appSource, /填写 Key/);
assert.match(appSource, /代理可选/);
assert.match(appSource, /测试后再上传/);
assert.match(indexHtml, /class="app-shell no-paper"/);
assert.match(indexHtml, /id="modelSettingsDetails"/);
assert.match(indexHtml, /id="emptyChooseButton"/);
assert.match(indexHtml, /id="taskRail"/);
assert.match(indexHtml, /id="primaryToolbarActionButton"/);
assert.match(indexHtml, /class="toolbar-menu"/);
assert.match(indexHtml, /把论文拖进来，然后开始精读/);
assert.match(appSource, /setHistoryOpen\(true\)/);
assert.match(appSource, /els\.analysisDashboard\.replaceChildren\(\)/);
assert.match(appSource, /function renderTaskRail/);
assert.match(appSource, /function buildTaskRailModel/);
assert.match(appSource, /function getPrimaryToolbarAction/);
assert.match(appSource, /function runPrimaryToolbarAction/);
assert.match(appSource, /function renderParagraphReadingPanel/);
assert.match(appSource, /function renderParagraphActionMenu/);
assert.match(appSource, /collapsedParagraphPanels/);
assert.match(appSource, /function submitParagraphQuestion/);
assert.match(appSource, /function retryParagraphQuestion/);
assert.match(appSource, /chat-retry-button/);
assert.match(appSource, /function renderPipelineQualityTrustSummary/);
assert.match(appSource, /这次结果能不能信/);
assert.match(appSource, /function renderPipelineQualityCategoryOverview/);
assert.match(appSource, /function buildPipelineQualityFilterChip/);
assert.match(appSource, /pipelineQualityFilter/);
assert.match(appSource, /aria-pressed/);
assert.match(appSource, /function renderPipelineLayoutDiagnostics/);
assert.match(appSource, /function getPipelineLayoutModeLabel/);
assert.match(appSource, /版面解析/);
assert.match(appSource, /function renderSegmentationDebugReview/);
assert.match(appSource, /function renderSegmentationDebugSectionMap/);
assert.match(appSource, /function renderSegmentationDebugParagraphActions/);
assert.match(appSource, /function createSegmentationDebugParagraphAction/);
assert.match(appSource, /保留正文/);
assert.match(appSource, /章节地图/);
assert.match(appSource, /合并下段/);
assert.match(appSource, /promptSplitParagraph\(paragraph\)/);
assert.match(serverSource, /function createRecoverableFilteredParagraphId/);
assert.match(serverSource, /recoverable-filtered/);
assert.match(serverSource, /createHash\("sha1"\)/);
assert.match(appSource, /checks\.filter\(\(check\) => check\?\.severity === "warn"\)\.length/);
assert.match(appSource, /button\.textContent = "说明"/);
assert.match(appSource, /check\.category === "pipeline"/);
assert.match(appSource, /正在停止自动讲解/);
assert.match(appSource, /查看问题/);
assert.match(appSource, /retryFailedJob\(retryableJob\.id\)/);
assert.match(appStyles, /\.app-shell\.no-paper \.reader-toolbar-main/);
assert.match(appStyles, /\.empty-start/);
assert.match(appStyles, /\.task-rail/);
assert.match(appStyles, /\.toolbar-groups/);
assert.match(appStyles, /\.toolbar-primary-action/);
assert.match(appStyles, /\.toolbar-menu:not\(\[open\]\) > \.toolbar-menu-panel/);
assert.match(appStyles, /\.paragraph-reading-panel/);
assert.match(appStyles, /\.paragraph-action-menu/);
assert.match(appStyles, /\.chat-message-actions/);
assert.match(appStyles, /\.chat-retry-button/);
assert.match(appStyles, /\.pipeline-trust-summary/);
assert.match(appStyles, /\.pipeline-quality-category-chip/);
assert.match(appStyles, /\.pipeline-quality-category-chip\.active/);
assert.match(appStyles, /\.pipeline-quality-empty/);
assert.match(appStyles, /\.pipeline-layout-diagnostics/);
assert.match(appStyles, /\.pipeline-layout-mode/);
assert.match(appStyles, /\.segmentation-debug-review/);
assert.match(appStyles, /\.segmentation-debug-section-map/);
assert.match(appStyles, /\.segmentation-debug-paragraph-actions/);
assert.match(appStyles, /\.segmentation-debug-paragraph-action/);
